SpeedoModels/Models/Order.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SpeedoModels.Models
{
    /// <summary>
    /// Class Order.
    /// </summary>
    public class Order
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the customer identifier.
        /// </summary>
        /// <value>The customer identifier.</value>
        [Required]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or sets the tracking number.
        /// </summary>
        /// <value>The tracking number.</value>
        public int TrackingNumber { get; set; }

        /// <summary>
        /// Gets or sets the order date.
        /// </summary>
        /// <value>The order date.</value>
        [DataType(DataType.Date)]
        public DateTime OrderDate { get; set; }

        /// <summary>
        /// Gets or sets the date of return.
        /// </summary>
        /// <value>The date of return.</value>
        public DateTime DateOfReturn { get; set; }

        /// <summary>
        /// Gets or sets the reason for return.
        /// </summary>
        /// <value>The reason for return.</value>
        public string ReasonForReturn { get; set; }

        /// <summary>
        /// Gets or sets the condition of item.
        /// </summary>
        /// <value>The condition of item.</value>
        public string ConditionOfItem { get; set; }

        /// <summary>
        /// Gets or sets the order lines.
        /// </summary>
        /// <value>The order lines.</value>
        public ICollection<Orderline> OrderLines { get; set; }

        /// <summary>
        /// Gets or sets the order total.
        /// </summary>
        /// <value>The order total.</value>
        [Required]
        public decimal OrderTotal { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is cancelled.
        /// </summary>
        /// <value><c>true</c> if this instance is cancelled; otherwise, <c>false</c>.</value>
        public bool IsCancelled { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Order"/> class.
        /// </summary>
        public Order()
        {
            DateOfReturn = DateTime.Parse("01/01/2000");
            OrderDate = DateTime.Parse("01/01/2000");
            TrackingNumber = 0;
            ReasonForReturn = "";
            ConditionOfItem = "";
            OrderLines = null;
            OrderTotal = 0;
        }
    }
}

SpeedoModels/Controllers/Api/OrderController.cs
// ***********************************************************************
// Assembly         : SpeedoModels
// Author           : Michael Haughian
// Created          : 05-10-2018
//
// Last Modified By : Michael Haughian
// Last Modified On : 05-30-2018
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using SpeedoModels.Models;
using Microsoft.AspNet.Identity;

namespace SpeedoModels.Controllers.Api
{
    /// <summary>
    /// Class OrderController.
    /// </summary>
    /// <seealso cref="System.Web.Http.ApiController" />
    public class OrderController : ApiController
    {
        /// <summary>
        /// The context
        /// </summary>
        private ApplicationDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderController" /> class.
        /// </summary>
        public OrderController()
        {
            _context = new ApplicationDbContext();
        }

        /// <summary>
        /// Releases the unmanaged resources that are used by the object and, optionally, releases the managed resources.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        /// <summary>
        /// Views the orders.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IHttpActionResult.</returns>
        [System.Web.Http.HttpGet]
        public IHttpActionResult ViewOrders(string id)
        {

            var orders = _context.Orders.Where(c => c.CustomerId == id).ToList();

            //if user is an admin or staff, return all orders, if logged in only return orders related to that customer
            if (User.IsInRole("Admin") || User.IsInRole("Staff"))
            {
                orders = _context.Orders.ToList();

                return Ok(orders);
            }
            else 
            {
                foreach (Order order in orders.ToList())
                {
                    if (order.IsCancelled)
                    {
                        orders.Remove(order);
                    }
                }
            }
            

            return Ok(orders);
        }

        /// <summary>
        /// Views the order.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IHttpActionResult.</returns>
        [System.Web.Http.HttpGet]
        [System.Web.Http.Route("api/order/vieworder/{id}")]
        public IHttpActionResult ViewOrder(int id)
        {
            var order = _context.Orders.SingleOrDefault(c => c.Id== id);

            return Ok(order);
        }

        /// <summary>
        /// Creates the order.
        /// </summary>
        /// <param name="basket">The basket.</param>
        [System.Web.Http.HttpPost]
        public void CreateOrder(Basket basket)
        {
            Order order = new Order();
            Payment payment = new Payment();
            List<Orderline> orderlines = new List<Orderline>();

            //creating order details from basket
            order.CustomerId = basket.CustomerId;
            order.OrderDate = DateTime.Now.Date;

            //generates random number for tracking number
            Random rnd = new Random();
            order.TrackingNumber = rnd.Next(100000000, 999999999);

            //creates an orderline for each product in the basket
            foreach (Product product in basket.Products)
            {
                Orderline orderline = new Orderline();

                orderline.Product = product;
                orderline.Quantity = product.Quantity;
                orderline.LineTotal = product.Price * product.Quantity;
                order.OrderTotal += orderline.LineTotal;

                orderlines.Add(orderline);

                Product loadedProduct = _context.Products.SingleOrDefault(c => c.Id == product.Id);

                loadedProduct.Stock -= product.Quantity;

                _context.SaveChanges();

            }

            _context.Orders.Add(order);

            try
            {
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                Debug.WriteLine("ERROR: " + ex);
            }

            //after adding order to the database, get the orders id and add it to the orderlines orderid and then saves to the database
            foreach (Orderline orderline in orderlines)
            {
                orderline.OrderId = order.Id;
                orderline.ProductId = orderline.Product.Id;
                orderline.Product = null;
                _context.Orderlines.Add(orderline);
            }

            //creates and saves payment information
            payment.CustomerId = order.CustomerId;
            payment.OrderId = order.Id;
            payment.PaymentTotal = order.OrderTotal;
            payment.PaymentDate = DateTime.Now.Date;

            _context.Payments.Add(payment);

            try
            {
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                Debug.WriteLine("ERROR: " + ex);
            }
        }

        /// <summary>
        /// Cancels the order.
        /// </summary>
        /// <param name="id">The identifier.</param>
        [System.Web.Http.HttpDelete]
        public void CancelOrder(int id)
        {
            var order = _context.Orders.SingleOrDefault(c => c.Id == id);
            order.OrderLines = _context.Orderlines.Where(c => c.OrderId == id).ToList();
            var product = new Product();

            //sets order to cancelled
            order.IsCancelled = true;

            //for each orderline of order that was cancelled, increase product stock
            foreach (Orderline orderline in order.OrderLines)
            {
                product = _context.Products.SingleOrDefault(c => c.Id == orderline.ProductId);
                product.Stock += orderline.Quantity;
            }

            _context.SaveChanges();
        }
    }
}

SpeedoModels/Controllers/OrderController.cs
// ***********************************************************************
// Assembly         : SpeedoModels
// Author           : Michael Haughian
// Created          : 05-10-2018
//
// Last Modified By : Michael Haughian
// Last Modified On : 05-30-2018
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using SpeedoModels.Models;
using Stripe;

namespace SpeedoModels.Controllers
{
    /// <summary>
    /// Class OrderController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    [Authorize]
    public class OrderController : Controller
    {
        // GET: Order
        /// <summary>
        /// Orders the page.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult OrderPage()
        {
            //sets previous page to empty
            Session["Referrer"] = "";

            //gets stripe publishable key and sets it to the viewbag
            var stripePublishKey = ConfigurationManager.AppSettings["stripePublishableKey"];
            ViewBag.StripePublishKey = stripePublishKey;

            return View();
        }

        /// <summary>
        /// Submits the order.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult SubmitOrder()
        {
            return View();
        }

        /// <summary>
        /// Views the orders.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult ViewOrders(string id)
        {
            if (id.Equals("0"))
            {
                id = User.Identity.GetUserId();
            }

            ViewBag.userId = JsonConvert.SerializeObject(id);

            return View();
        }

        /// <summary>
        /// Views the order.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult ViewOrder(int id)
        {
            ViewBag.orderId = JsonConvert.SerializeObject(id);

            return View();
        }

        /// <summary>
        /// Charges the specified stripe email.
        /// </summary>
        /// <param name="stripeEmail">The stripe email.</param>
        /// <param name="stripeToken">The stripe token.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Charge(string stripeEmail, string stripeToken)
        {
            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            Basket basket;
            var cookie = Request.Cookies["Basket"];

            //try and retrieve basket, if empty and causes exception create new basket
            try
            {
                basket = new JavaScriptSerializer().Deserialize<Basket>(cookie.Value);
            }
            catch
            {
                basket = new Basket();
            }

            decimal basketTotal = 0;
            
            foreach (Product product in basket.Products.ToList())
            {
                for (int i = 1; i <= product.Quantity; i++)
                {
                    basketTotal += product.Price;
                }
            }

            //changes basketTotal to an integer as amount needs to be an int
            int amount = (int)(basketTotal * 100);

            //methods for creating stripe payment
            var customer = customers.Create(new StripeCustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new StripeChargeCreateOptions
            {
                Amount = amount, //charge in pence
                Description = "Speedo Models Checkout",
                Currency = "gbp",
                CustomerId = customer.Id
            });

            

            return View("SubmitOrder");
        }

    }
}

SpeedoModels/Controllers/ProductController.cs
// ***********************************************************************
// Assembly         : SpeedoModels
// Author           : Michael Haughian
// Created          : 04-11-2018
//
// Last Modified By : Michael Haughian
// Last Modified On : 05-29-2018
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using SpeedoModels.Models;
using SpeedoModels.ViewModels;
using System.Data.Entity;
using System.Net.Http;

namespace SpeedoModels.Controllers
{
    /// <summary>
    /// Class ProductController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class ProductController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private ApplicationDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductController" /> class.
        /// </summary>
        public ProductController()
        {
            _context = new ApplicationDbContext();
        }

        /// <summary>
        /// Releases unmanaged resources and optionally releases managed resources.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Index()
        {
            return View("StaffProductList");
        }

        /// <summary>
        /// Views the products.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult ViewProducts()
        {
            

            return View();
        }

        /// <summary>
        /// Views the product.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult ViewProduct(int id)
        {
            ViewBag.productId = id;

            return View();
        }

        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Edit(int id)
        {
            ViewBag.productId = id;

            return View();
        }

        /*[HttpPost]
        public ActionResult Create(Product product)
        {
            //if ModelState isn't valid, redirect to create product page so use can try again
            if (!ModelState.IsValid)
            {
                var viewModel = new CreateProductViewModel(product)
                {
                    Suppliers = _context.Suppliers.ToList()
                };

                return View(viewModel);
            }

            if (product.Id == 0)
            {
                _context.Products.Add(product);
                _context.SaveChanges();
            }

            return ("Create");
        }*/
    }
}

SpeedoModels/Views/Order/OrderPage.cshtml
@{
    ViewBag.Title = "OrderPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OrderPage</h2>

<head>
    @*tried to get paypal working, checkout page wouldn't stay open
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>*@
</head>

<form id="orderForm" action="/order/charge" method="POST">

    <article>
        <label id="stripeAmount"></label>
    </article>
    <script id="stripeScript" src="//checkout.stripe.com/v2/checkout.js"
            class="stripe-button"
            data-key="@ViewBag.StripePublishKey"
            data-locale="auto"
            data-description="Checkout"
            data-amount="">
    </script>
    <br/>
    
</form>

@section scripts
{
    <script>
        $(document).ready(function () {
            var orderTotal;
            $.ajax({
                url: "/basket/getbasket/",
                method: "GET",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (basket) {
                    orderTotal = 0;
                    //for each product create html for order page
                    $.each(basket.Products, function (k, v) {
                        $("#orderForm").append("<div id='productDiv'>",
                            "<label>Product Name: </label> <input id='name" + v.Id + "' name='Name' disabled> </input>",
                            "<label>Product Description: </label> <input id='description" + v.Id + "' name='Description' disabled> </input>",
                            "<label>Product Price: </label> <input id='price" + v.Id + "' name='Price' disabled> </input>",
                            "<label>Quantity: </label> <input id='quantity" + v.Id + "' name='Quantity' disabled> </input>",
                            "</div>",
                            "<br>");
                        $('#name' + v.Id).val(v.Name);
                        $("#description" + v.Id).val(v.Description);
                        $("#price" + v.Id).val(v.Price);
                        $("#quantity" + v.Id).val(v.Quantity);
                        orderTotal += (v.Price * v.Quantity);
                    });     
                }
            }).done(function() {
                $("#stripeAmount").text("Amount: £" + orderTotal);
            }); 
        });  
    </script>
}

SpeedoModels/Views/Order/SubmitOrder.cshtml
@{
    ViewBag.Title = "SubmitOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ORDER SUBMITTED</h1>

<text>You will be redirected soon</text>

<div id="smsSettings">
    <input type="hidden" id="smsNumber" value=""/>
</div>
<div>

</div>

@section scripts
{
    <script>
        $(document).ready(function() {
            $.ajax({
                url: "/basket/getbasket/",
                method: "GET",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function(basket) {
                    $.ajax({
                        url: "/api/order/",
                        method: "POST",
                        data: JSON.stringify(basket),
                        contentType: "application/json",
                        traditional: true,
                        processData: false
                    }).done(function () {
                            $.ajax({
                                url: "/mail/SendOrderConfirmation",
                                method: "POST"
                            });
     
                            @*$.ajax({
                                url: "/SMS/SendOrderMessage",
                                method: "POST"
                            });*@
                        $.ajax({
                            url: "/basket/clearbasket",
                            method: "POST"
                        }).done(function() {
                            setTimeout(
                                function () {
                                    var baseUrl="@Url.Action("ViewProducts","Product")";
                                    window.location.href=baseUrl;
                                }, 2000);
                        });
                    }).fail(function() {
                        toastr.error("NOPE");
                    });
                }
            });
        });
    </script>
}

SpeedoModels/Views/Order/ViewOrder.cshtml
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "ViewOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Order</h2>

<button class="btn btn-primary" id="return" name="Return">Return to Orders</button>

<table id="orderLines" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Product</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>


@section scripts
{
    <script>
        $(document).ready(function() {
            var table = $("#orderLines").DataTable({
                ajax: {
                    url: "/api/orderline/" + @Html.Raw(ViewBag.orderId),
                    method: "GET",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "Product.Name"
                    },
                    {
                        data: "Product.Description"
                    },
                    {
                        data: "Quantity"
                    },
                    {
                        data: "Product.Price"
                    },
                    {
                        data: "LineTotal"
                    }
                ]
            });

            $("#return").click(function(e) {
                e.preventDefault();
                var baseUrl="@Url.Action("ViewOrders","Order", new { id = HttpContext.Current.User.Identity.GetUserId() },null)";
                window.location.href=baseUrl;
            });
        });


    </script>
}

SpeedoModels/Views/Order/ViewOrders.cshtml
@{
    ViewBag.Title = "ViewOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Orders</h2>
<table id="orders" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Order Id</th>
        <th>Tracking Number</th>
        <th>Order Total</th>
        <th>Order Date</th>
        <th>View</th>
        <th>Cancel Order</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>


@section scripts
{
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>

    <script>
        $(document).ready(function () {
            $.ajax({
                url: "/api/order/" + @Html.Raw(ViewBag.userId),
                method: "GET"
            }).done(function(result) {
                if (result.length === 0) {
                    bootbox.alert("No orders have been created on this account");
                }
            });

            var table = $("#orders").DataTable({
                ajax: {
                    url: "/api/order/" + @Html.Raw(ViewBag.userId),
                    method: "GET",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "Id"
                    },
                    {
                        data: "TrackingNumber"
                    },
                    {
                        data: "OrderTotal"
                    },
                    {
                        data: "OrderDate",
                        render: function(d){
                            return moment(d).format("DD/MM/YYYY");
                        }
                    },
                    {
                        data: "Id",
                        render: function(data) {
                            console.log(data);
                            return "<a href='/order/vieworder/" + data + "' class='btn btn-primary'>View</a>";
                        }
                    },
                    {
                        data: "Id",
                        render: function(data) {
                            return "<button id='cancel' data-internalid='"+data+"' class='btn btn-primary js-cancel'>Cancel</button>";
                        }
                    }
                ]


            });

            
            
            
            //on click attempt to cancel an order. if the date is within 48 hours of being placed you will be able to cancel it.
            $(document).on("click", ".js-cancel",
                function() {
                    var buttonId = $(this).attr("data-internalid");
                    $.ajax({
                        url: "/api/order/vieworder/" + buttonId,
                        method: "GET"
                    }).done(function(order) {
                        var d = new Date();
                        var od = new Date(order.OrderDate);
                        od.setDate(od.getDate() + 2);
                        if (d > od) {
                            bootbox.alert("Unable to cancel order after 48 hours");
                            
                        } 
                        else if(d < od)
                        {
                            bootbox.confirm("Are you sure you want to cancel this order?",
                                function(confirmed) {
                                    if (confirmed) {
                                        $.ajax({
                                            url: "/mail/sendordercancellation/",
                                            method: "POST"
                                        });
                                        $.ajax({
                                            url: "/api/order/" + buttonId,
                                            method: "DELETE"
                                        }).done(function() {
                                            $.ajax({
                                                url: "/SMS/SendCancelMessage",
                                                method: "POST"
                                            });
                                            window.location.reload();
                                        }).fail(function() {
                                            toastr.error("Something unexpected happened");
                                        });
                                    }
                                });
                        };

                    });
                    
                });
        });
            


    </script>
}